# ========================================
# ⚡ POWERLEVEL10K INSTANT PROMPT
# ========================================
# Must be at the top, before any other code
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# ========================================
# 🔧 ZSH CONFIGURATION
# ========================================

# Enable proper expansion mode
setopt EXTENDED_GLOB

# Enable quick correction
setopt CORRECT

source_if_exists() {
  local file="$1"
  [[ -f "$file" ]] && source "$file"
}

# ========================================
# 🧱 RC MODULES
# ========================================
source_if_exists "$ZDOTDIR/rc/aliases.zsh"
source_if_exists "$ZDOTDIR/rc/history.zsh"
source_if_exists "$ZDOTDIR/rc/zinit.zsh"

# ========================================
# 🎨 POWERLEVEL10K (modern theme)
# ========================================
source ~/.zsh/themes/powerlevel10k/powerlevel10k.zsh-theme

# Load saved configuration (generated by `p10k configure`)
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# ========================================
# 🔄 COMPLETIONS (npm, docker, git, etc)
# ========================================

# Add extra completions to fpath
fpath=(~/.zsh/completions/zsh-completions/src $fpath)

# Enable completion system
autoload -Uz compinit
if [[ -n $HOME/.zcache/zcompdump(#qN.mh+24) ]]; then
  compinit -C  # faster when cache is recent
else
  mkdir -p $HOME/.zcache
  compinit -d $HOME/.zcache/zcompdump
fi

# Completion settings
zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}' 'r:[^[:space:]][]=[^[:space:]][]' 'l:|=* r:|=*'
zstyle ':completion:*:descriptions' format '%F{yellow}⮞ %d%f'
zstyle ':completion:*:warnings' format '%F{red}⚠ No matches found%f'
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path "$HOME/.zcache/completion"

# Enable npm completion (without echo during init)
if command -v npm >/dev/null 2>&1; then
  npm completion >/dev/null 2>&1
fi

# ========================================
# 💡 BASIC PROMPT (fallback - p10k overrides)
# ========================================
PROMPT='%F{blue}%n@%m%f %F{green}%~%f %# '

# ========================================
# 🐚 OTHER USEFUL OPTIONS
# ========================================

# ========================================
# 🚀 EXTERNAL TOOLS
# ========================================

# fnm
FNM_PATH="/home/vagners/.local/share/fnm"
if [ -d "$FNM_PATH" ]; then
  export PATH="$FNM_PATH:$PATH"
  eval "`fnm env`"
fi

# SDKMAN
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# ========================================
# 🎯 EXTERNAL COMPLETIONS (keep only one block)
# ========================================
###-begin-npm-completion-###
if type complete &>/dev/null; then
  _npm_completion () {
    local words cword
    if type _get_comp_words_by_ref &>/dev/null; then
      _get_comp_words_by_ref -n = -n @ -n : -w words -i cword
    else
      cword="$COMP_CWORD"
      words=("${COMP_WORDS[@]}")
    fi

    local si="$IFS"
    if ! IFS=$'\n' COMPREPLY=($(COMP_CWORD="$cword" \
                           COMP_LINE="$COMP_LINE" \
                           COMP_POINT="$COMP_POINT" \
                           npm completion -- "${words[@]}" \
                           2>/dev/null)); then
      local ret=$?
      IFS="$si"
      return $ret
    fi
    IFS="$si"
    if type __ltrim_colon_completions &>/dev/null; then
      __ltrim_colon_completions "${words[cword]}"
    fi
  }
  complete -o default -F _npm_completion npm
elif type compdef &>/dev/null; then
  _npm_completion() {
    local si=$IFS
    compadd -- $(COMP_CWORD=$((CURRENT-1)) \
                 COMP_LINE=$BUFFER \
                 COMP_POINT=0 \
                 npm completion -- "${words[@]}" \
                 2>/dev/null)
    IFS=$si
  }
  compdef _npm_completion npm
elif type compctl &>/dev/null; then
  _npm_completion () {
    local cword line point words si
    read -Ac words
    read -cn cword
    let cword-=1
    read -l line
    read -ln point
    si="$IFS"
    if ! IFS=$'\n' reply=($(COMP_CWORD="$cword" \
                       COMP_LINE="$line" \
                       COMP_POINT="$point" \
                       npm completion -- "${words[@]}" \
                       2>/dev/null)); then
      local ret=$?
      IFS="$si"
      return $ret
    fi
    IFS="$si"
  }
  compctl -K _npm_completion npm
fi
###-end-npm-completion-###

# ========================================
# 🎉 FINAL MESSAGES (after full load)
# ========================================
# Only if running in an interactive terminal and instant prompt has finished
if [[ -t 1 ]] && { [[ -z "$P10K_INSTANT_PROMPT_ACTIVE" ]] || [[ "$P10K_INSTANT_PROMPT_ACTIVE" != "1" ]]; }; then
  echo
  echo -e "\e[32m✅ Zsh loaded successfully!\e[0m"
  echo -e "\e[34m💡 Tip:\e[0m Use \e[1m'p10k configure'\e[0m to customize the theme"
  echo -e "\e[33m🚀 Ready to code!\e[0m"
  echo
fi




export PATH=$PATH:/usr/local/go/bin
export GOPATH=/home/vagners/homebrew/go
export PATH=$PATH:$GOPATH/bin

. "$HOME/.local/bin/env"
